package io.gaiaid.registry.enums;

public enum CreateStep {
	CITIZEN_ID,
	FIRSTNAME, 
	LASTNAME,
	AVATARNAME,
	AVATARPIC,
	BIRTHDATE, 
	PLACE_OF_BIRTH, 
	PENDING_CONFIRM,
	WANT_TO_CHANGE,
	NEED_TO_CHANGE,
	CHANGE_CITIZEN_ID, 
	CHANGE_FIRSTNAME, 
	CHANGE_LASTNAME, 
	CHANGE_AVATARNAME,
	CHANGE_AVATARPIC,
	CHANGE_BIRTHDATE, 
	CHANGE_PLACE_OF_BIRTH, 
	CAPTURE,
	PASSWORD, 
	FACE_CAPTURE, 
	FACE_VERIFICATION,
	FINGERPRINT_CAPTURE, 
	FINGERPRINT_VERIFICATION,
	ISSUE
	
	
}
