package io.gaiaid.registry.enums;

public enum RestoreStep {
	KNOW_ID, INPUT_ID, 
	
	CITIZEN_ID,
	FIRSTNAME, LASTNAME, AVATARNAME, BIRTHDATE, PLACE_OF_BIRTH, METHOD, PASSWORD, FACE_VERIFICATION, FINGERPRINT_VERIFICATION, ISSUE, DONE
}
