version: '3.3'

services:
  service-agent:
    
    image: gitlab.mobiera.com:4567/2060/2060-service-agent:dev

    networks:
      - chatbot
    ports:
      - 2600:3000
      - 2601:3001
    environment:
      - AGENT_PUBLIC_DID=did:web:p2601.ovpndev.2060.io
      - AGENT_ENDPOINT=wss://p2601.ovpndev.2060.io
      - AGENT_INVITATION_IMAGE_URL=https://p2601.ovpndev.2060.io/avatar.png
      - AGENT_NAME=Chatbot Java Demo Agent
      - USE_CORS=true
      - EVENTS_BASE_URL=http://demo-chatbot:2900
    volumes:
       - ./afj:/root/.afj
  demo-chatbot:
    image: gitlab.mobiera.com:4567/2060/2060-demo-chatbot-java:1.0.0-SNAPSHOT
    networks:
      - chatbot
    ports:
      - 2900:2900
    environment:
      - DEBUG=1
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_PORT=2900
      - IO_TWENTYSIXTY_DEMO_CHATBOT_RES_C_MESSAGERESOURCE_MP_REST_URL=http://service-agent:3000
      - PNVS_SERVICE_AGENT_ADMIN_BASE_URL=https://a.pn-vs.dev.2060.io
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres/guess
 
  postgres:
    image: postgresql:15.2
    networks:
      - chatbot
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=2060demo
      - POSTGRES_USER=guess
networks:
  chatbot:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/27
