apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: email-verification-service
   namespace: 2060-dev
   labels:
      app: nginx
spec:
   serviceName: "email-verification-service"
   replicas: 1
   selector:
      matchLabels:
         app: email-verification-service
   template:
      metadata:
         labels:
            app: email-verification-service
      spec:
         containers:
         -  name: email-verification-service-sa-container
            image: gitlab.mobiera.com:4567/2060/2060-service-agent:dev
            imagePullPolicy: Always
            env:
            - name: AGENT_ENDPOINT
              value: "wss://em-vs.dev.2060.io:443"
            - name: AGENT_NAME
              value: "Email Verification Service (dev)"
            - name: AGENT_INVITATION_IMAGE_URL
              value: "https://q.em-vs.dev.2060.io/avatar.png"
            - name: EVENTS_BASE_URL
              value: "http://localhost:2902"
            - name: AGENT_PUBLIC_DID
              value: "did:web:em-vs.dev.2060.io"
            - name: ANONCREDS_SERVICE_BASE_URL
              value: "https://em-vs.dev.2060.io"
            volumeMounts:
            - name: email-verification-service-sa-pv-dev
              mountPath: /root/.afj
            ports:
            -  containerPort: 3000
            -  containerPort: 3001
         -  name: email-verification-service-backend-container
            image: gitlab.mobiera.com:4567/2060/demos/2060-email-verification-service:dev
            imagePullPolicy: Always
            env:
            - name: SERVICE_AGENT_ADMIN_BASE_URL
              value: "http://localhost:3000"
            - name: PUBLIC_BASE_URL
              value: "https://em-vs.dev.2060.io"
            - name: PNVS_SERVICE_AGENT_ADMIN_BASE_URL
              value: "https://a.pn-vs.dev.2060.io"
            - name: DEBUG
              value: "1"
            - name: QUARKUS_HTTP_PORT
              value: "2902"
            - name: IO_TWENTYSIXTY_SA_RES_C_MESSAGERESOURCE_MP_REST_URL
              value: "http://localhost:3000"
            - name: IO_TWENTYSIXTY_SA_RES_C_CREDENTIALTYPERESOURCE_MP_REST_URL
              value: "http://localhost:3000"
            ports:
            -  containerPort: 2902
         -  name: postgres
            image: postgres:15.2
            imagePullPolicy: Always
            env:
            - name: POSTGRES_PASSWORD
              value: "2060demo"
            - name: POSTGRES_USER
              value: "emailvs"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            ports:
            -  containerPort: 5432
            volumeMounts:
            - name: email-verification-service-pg-pv-dev
              mountPath: /var/lib/postgresql/data
         imagePullSecrets:
         -  name: dev-registry-credentials

   volumeClaimTemplates:
   - metadata:
       name: email-verification-service-sa-pv-dev
     spec:
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
   - metadata:
       name: email-verification-service-pg-pv-dev
     spec:
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
