## A basic GitHub Actions workflow for your Quarkus application.

name: CI build citizen-registry

on:
  push:
    branches: [ dev ]
    paths:
    - 'citizen-registry/**'
    - '.github/workflows/ci-citizen-registry.yml'
  pull_request:
    branches: [ main, dev ]
    paths: 
    - 'citizen-registry/**'
    - '.github/workflows/ci-citizen-registry.yml'
  workflow_dispatch:

env:
  QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}
  QUARKUS_CONTAINER_IMAGE_TAG: ${GITHUB_REF_NAME}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        
      - name: Build
        run: |
          cd citizen-registry
          ./mvnw package -B
          docker image ls
