## A basic GitHub Actions workflow for your Quarkus application.

name: CI build email-verification-service

on:
  push:
    branches: [ dev ]
    paths:
    - 'email-verification-service/**'
    - '.github/workflows/ci-email-verification-service.yml'
  pull_request:
    branches: [ main, dev ]
    paths: 
    - 'email-verification-service/**'
    - '.github/workflows/ci-email-verification-service.yml'
  workflow_dispatch:

env:
  QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        
      - name: Build
        run: |
          cd email-verification-service
          ./mvnw package -B -Dquarkus.container-image.tag=${GITHUB_REF##*/}
          docker image ls
