name: generate plantuml citizen-registry

on: 
  push:
    branches: [ dev ]
    paths:
    - 'citizen-registry/**'
    - '.github/workflows/plantuml-citizen-registry.yml'
  pull_request:
    branches: [ dev ]
    paths: 
    - 'citizen-registry/**'
    - '.github/workflows/plantuml-citizen-registry.yml'

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: .
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
